package com.java.xxii.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BAN_KEYWORD.
 */
public class BanKeyword {

    /** Not-null value. */
    private String Keyword;

    public BanKeyword() {
    }

    public BanKeyword(String Keyword) {
        this.Keyword = Keyword;
    }

    /** Not-null value. */
    public String getKeyword() {
        return Keyword;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKeyword(String Keyword) {
        this.Keyword = Keyword;
    }

}
