package com.java.xxii.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.java.xxii.greendao.BanKeyword;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BAN_KEYWORD.
*/
public class BanKeywordDao extends AbstractDao<BanKeyword, String> {

    public static final String TABLENAME = "BAN_KEYWORD";

    /**
     * Properties of entity BanKeyword.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Keyword = new Property(0, String.class, "Keyword", true, "KEYWORD");
    };


    public BanKeywordDao(DaoConfig config) {
        super(config);
    }
    
    public BanKeywordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BAN_KEYWORD' (" + //
                "'KEYWORD' TEXT PRIMARY KEY NOT NULL );"); // 0: Keyword
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_BAN_KEYWORD_KEYWORD ON BAN_KEYWORD" +
                " (KEYWORD);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BAN_KEYWORD'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BanKeyword entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getKeyword());
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BanKeyword readEntity(Cursor cursor, int offset) {
        BanKeyword entity = new BanKeyword( //
            cursor.getString(offset + 0) // Keyword
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BanKeyword entity, int offset) {
        entity.setKeyword(cursor.getString(offset + 0));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(BanKeyword entity, long rowId) {
        return entity.getKeyword();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(BanKeyword entity) {
        if(entity != null) {
            return entity.getKeyword();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
