package com.java.xxii.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.java.xxii.greendao.BanNews;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BAN_NEWS.
*/
public class BanNewsDao extends AbstractDao<BanNews, Long> {

    public static final String TABLENAME = "BAN_NEWS";

    /**
     * Properties of entity BanNews.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BanCollection_id = new Property(1, long.class, "banCollection_id", false, "BAN_COLLECTION_ID");
    };

    private DaoSession daoSession;

    private Query<BanNews> banCollection_BanNewsListQuery;

    public BanNewsDao(DaoConfig config) {
        super(config);
    }
    
    public BanNewsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BAN_NEWS' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'BAN_COLLECTION_ID' INTEGER NOT NULL );"); // 1: banCollection_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BAN_NEWS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BanNews entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getBanCollection_id());
    }

    @Override
    protected void attachEntity(BanNews entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BanNews readEntity(Cursor cursor, int offset) {
        BanNews entity = new BanNews( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1) // banCollection_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BanNews entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBanCollection_id(cursor.getLong(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BanNews entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BanNews entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "banNewsList" to-many relationship of BanCollection. */
    public List<BanNews> _queryBanCollection_BanNewsList(long banCollection_id) {
        synchronized (this) {
            if (banCollection_BanNewsListQuery == null) {
                QueryBuilder<BanNews> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.BanCollection_id.eq(null));
                banCollection_BanNewsListQuery = queryBuilder.build();
            }
        }
        Query<BanNews> query = banCollection_BanNewsListQuery.forCurrentThread();
        query.setParameter(0, banCollection_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBanCollectionDao().getAllColumns());
            builder.append(" FROM BAN_NEWS T");
            builder.append(" LEFT JOIN BAN_COLLECTION T0 ON T.'BAN_COLLECTION_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected BanNews loadCurrentDeep(Cursor cursor, boolean lock) {
        BanNews entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BanCollection banCollection = loadCurrentOther(daoSession.getBanCollectionDao(), cursor, offset);
         if(banCollection != null) {
            entity.setBanCollection(banCollection);
        }

        return entity;    
    }

    public BanNews loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<BanNews> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BanNews> list = new ArrayList<BanNews>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<BanNews> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<BanNews> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
