package com.java.xxii.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.java.xxii.greendao.NewsChannelTable;
import com.java.xxii.greendao.BanCollection;
import com.java.xxii.greendao.BanNews;

import com.java.xxii.greendao.NewsChannelTableDao;
import com.java.xxii.greendao.BanCollectionDao;
import com.java.xxii.greendao.BanNewsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsChannelTableDaoConfig;
    private final DaoConfig banCollectionDaoConfig;
    private final DaoConfig banNewsDaoConfig;

    private final NewsChannelTableDao newsChannelTableDao;
    private final BanCollectionDao banCollectionDao;
    private final BanNewsDao banNewsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsChannelTableDaoConfig = daoConfigMap.get(NewsChannelTableDao.class).clone();
        newsChannelTableDaoConfig.initIdentityScope(type);

        banCollectionDaoConfig = daoConfigMap.get(BanCollectionDao.class).clone();
        banCollectionDaoConfig.initIdentityScope(type);

        banNewsDaoConfig = daoConfigMap.get(BanNewsDao.class).clone();
        banNewsDaoConfig.initIdentityScope(type);

        newsChannelTableDao = new NewsChannelTableDao(newsChannelTableDaoConfig, this);
        banCollectionDao = new BanCollectionDao(banCollectionDaoConfig, this);
        banNewsDao = new BanNewsDao(banNewsDaoConfig, this);

        registerDao(NewsChannelTable.class, newsChannelTableDao);
        registerDao(BanCollection.class, banCollectionDao);
        registerDao(BanNews.class, banNewsDao);
    }
    
    public void clear() {
        newsChannelTableDaoConfig.getIdentityScope().clear();
        banCollectionDaoConfig.getIdentityScope().clear();
        banNewsDaoConfig.getIdentityScope().clear();
    }

    public NewsChannelTableDao getNewsChannelTableDao() {
        return newsChannelTableDao;
    }

    public BanCollectionDao getBanCollectionDao() {
        return banCollectionDao;
    }

    public BanNewsDao getBanNewsDao() {
        return banNewsDao;
    }

}
