package com.java.xxii.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.java.xxii.greendao.NewsChannelTable;
import com.java.xxii.greendao.BanCollection;
import com.java.xxii.greendao.BanNews;
import com.java.xxii.greendao.News;
import com.java.xxii.greendao.LikeNews;

import com.java.xxii.greendao.NewsChannelTableDao;
import com.java.xxii.greendao.BanCollectionDao;
import com.java.xxii.greendao.BanNewsDao;
import com.java.xxii.greendao.NewsDao;
import com.java.xxii.greendao.LikeNewsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsChannelTableDaoConfig;
    private final DaoConfig banCollectionDaoConfig;
    private final DaoConfig banNewsDaoConfig;
    private final DaoConfig newsDaoConfig;
    private final DaoConfig likeNewsDaoConfig;

    private final NewsChannelTableDao newsChannelTableDao;
    private final BanCollectionDao banCollectionDao;
    private final BanNewsDao banNewsDao;
    private final NewsDao newsDao;
    private final LikeNewsDao likeNewsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsChannelTableDaoConfig = daoConfigMap.get(NewsChannelTableDao.class).clone();
        newsChannelTableDaoConfig.initIdentityScope(type);

        banCollectionDaoConfig = daoConfigMap.get(BanCollectionDao.class).clone();
        banCollectionDaoConfig.initIdentityScope(type);

        banNewsDaoConfig = daoConfigMap.get(BanNewsDao.class).clone();
        banNewsDaoConfig.initIdentityScope(type);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        likeNewsDaoConfig = daoConfigMap.get(LikeNewsDao.class).clone();
        likeNewsDaoConfig.initIdentityScope(type);

        newsChannelTableDao = new NewsChannelTableDao(newsChannelTableDaoConfig, this);
        banCollectionDao = new BanCollectionDao(banCollectionDaoConfig, this);
        banNewsDao = new BanNewsDao(banNewsDaoConfig, this);
        newsDao = new NewsDao(newsDaoConfig, this);
        likeNewsDao = new LikeNewsDao(likeNewsDaoConfig, this);

        registerDao(NewsChannelTable.class, newsChannelTableDao);
        registerDao(BanCollection.class, banCollectionDao);
        registerDao(BanNews.class, banNewsDao);
        registerDao(News.class, newsDao);
        registerDao(LikeNews.class, likeNewsDao);
    }
    
    public void clear() {
        newsChannelTableDaoConfig.getIdentityScope().clear();
        banCollectionDaoConfig.getIdentityScope().clear();
        banNewsDaoConfig.getIdentityScope().clear();
        newsDaoConfig.getIdentityScope().clear();
        likeNewsDaoConfig.getIdentityScope().clear();
    }

    public NewsChannelTableDao getNewsChannelTableDao() {
        return newsChannelTableDao;
    }

    public BanCollectionDao getBanCollectionDao() {
        return banCollectionDao;
    }

    public BanNewsDao getBanNewsDao() {
        return banNewsDao;
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

    public LikeNewsDao getLikeNewsDao() {
        return likeNewsDao;
    }

}
