package com.java.xxii.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.java.xxii.greendao.NewsChannelTable;
import com.java.xxii.greendao.News;

import com.java.xxii.greendao.NewsChannelTableDao;
import com.java.xxii.greendao.NewsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsChannelTableDaoConfig;
    private final DaoConfig newsDaoConfig;

    private final NewsChannelTableDao newsChannelTableDao;
    private final NewsDao newsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsChannelTableDaoConfig = daoConfigMap.get(NewsChannelTableDao.class).clone();
        newsChannelTableDaoConfig.initIdentityScope(type);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        newsChannelTableDao = new NewsChannelTableDao(newsChannelTableDaoConfig, this);
        newsDao = new NewsDao(newsDaoConfig, this);

        registerDao(NewsChannelTable.class, newsChannelTableDao);
        registerDao(News.class, newsDao);
    }
    
    public void clear() {
        newsChannelTableDaoConfig.getIdentityScope().clear();
        newsDaoConfig.getIdentityScope().clear();
    }

    public NewsChannelTableDao getNewsChannelTableDao() {
        return newsChannelTableDao;
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

}
