package com.java.xxii.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LIKE_NEWS.
 */
public class LikeNews {

    /** Not-null value. */
    private String News_Id;
    /** Not-null value. */
    private String News_Title;
    /** Not-null value. */
    private String News_Time;
    /** Not-null value. */
    private String News_Img;
    private String News_Intro;
    private long add_Time;

    public LikeNews() {
    }

    public LikeNews(String News_Id) {
        this.News_Id = News_Id;
    }

    public LikeNews(String News_Id, String News_Title, String News_Time, String News_Img, String News_Intro, long add_Time) {
        this.News_Id = News_Id;
        this.News_Title = News_Title;
        this.News_Time = News_Time;
        this.News_Img = News_Img;
        this.News_Intro = News_Intro;
        this.add_Time = add_Time;
    }

    /** Not-null value. */
    public String getNews_Id() {
        return News_Id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNews_Id(String News_Id) {
        this.News_Id = News_Id;
    }

    /** Not-null value. */
    public String getNews_Title() {
        return News_Title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNews_Title(String News_Title) {
        this.News_Title = News_Title;
    }

    /** Not-null value. */
    public String getNews_Time() {
        return News_Time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNews_Time(String News_Time) {
        this.News_Time = News_Time;
    }

    /** Not-null value. */
    public String getNews_Img() {
        return News_Img;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNews_Img(String News_Img) {
        this.News_Img = News_Img;
    }

    public String getNews_Intro() {
        return News_Intro;
    }

    public void setNews_Intro(String News_Intro) {
        this.News_Intro = News_Intro;
    }

    public long getAdd_Time() {
        return add_Time;
    }

    public void setAdd_Time(long add_Time) {
        this.add_Time = add_Time;
    }

}
